import { createServer } from "node:http";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve, extname, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";

const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, "../..");
const cache = resolve(directory, ".cache");
const port = Number(process.env.PORT || 8422);
const config = {
  width: 600, height: 360, columns: 12, quality: 0.68, compensationPixels: 40,
  views: [{ id: "overview", frames: 96 }, { id: "library", frames: 32 }],
};
const sourceFiles = ["island-layout.js", "coastlines.js", ...["palette", "primitives", "materials", "models", "create-island-scene", "animation", "camera-presets", "camera", "renderer"].map(name => `scene/${name}.js`)];
const sources = await Promise.all(sourceFiles.map(file => readFile(resolve(root, "dist", file))));
config.sourceHash = createHash("sha256").update(Buffer.concat(sources)).digest("hex");
await mkdir(cache, { recursive: true });

function position(index) {
  return `translate(${-(index % config.columns) * config.width}px, ${-Math.floor(index / config.columns) * config.height}px)`;
}

async function build() {
  const atlases = await Promise.all(config.views.map(async view => ({ ...view, data: await readFile(resolve(cache, `${view.id}.webp`)) })));
  const overviewKeys = Array.from({ length: 97 }, (_, i) => `${(i / 96 * 100).toFixed(5)}%{transform:${position(i % 96)}}`).join("");
  // Approach, dwell at the library, and return. Reuse the same 32 frames.
  const libraryKeys = [];
  for (let i = 0; i < 32; i++) libraryKeys.push(`${(i / 31 * 40).toFixed(5)}%{transform:${position(i)}}`);
  libraryKeys.push(`85%{transform:${position(31)}}`);
  for (let i = 1; i < 32; i++) libraryKeys.push(`${(85 + i / 31 * 15).toFixed(5)}%{transform:${position(31 - i)}}`);
  const defs = atlases.map(view => `<image id="atlas-${view.id}" width="${config.columns * config.width}" height="${Math.ceil(view.frames / config.columns) * config.height}" href="data:image/webp;base64,${view.data.toString("base64")}"/>`).join("\n");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400" role="img" aria-labelledby="title desc">
<title id="title">Jasvir's island — overview and library</title>
<desc id="desc">Views rendered from the original Three.js island. The overview rotates; the library view approaches SecretSeal's reading room. Reduced motion shows still views.</desc>
<metadata>Source SHA-256: ${config.sourceHash}; generated by the profile export experiment.</metadata>
<style>
.view{display:none}#overview{display:inline}#library:target{display:inline}#library:target~#overview{display:none}
.orbit{animation:orbit 20s steps(1,end) infinite;transform:${position(0)}}
.approach{animation:approach 8s steps(1,end) infinite;transform:${position(31)}}
@keyframes orbit{${overviewKeys}}
@keyframes approach{${libraryKeys.join("")}}
@media(prefers-reduced-motion:reduce){.orbit,.approach{animation:none}}
</style>
<defs><clipPath id="frame"><rect width="600" height="360"/></clipPath>
${defs}</defs>
<g id="library" class="view"><g clip-path="url(#frame)"><use href="#atlas-library" class="approach"/></g></g>
<g id="overview" class="view"><g transform="translate(0 ${config.compensationPixels})"><g clip-path="url(#frame)"><use href="#atlas-overview" class="orbit"/></g></g></g>
</svg>\n`;
  await writeFile(resolve(directory, "island.svg"), svg);
  const manifest = {
    sourceHash: config.sourceHash, sourceFiles, width: 600, height: 400,
    svgBytes: Buffer.byteLength(svg), gzipBytes: gzipSync(svg).length,
    frames: config.views.reduce((sum, view) => sum + view.frames, 0),
    views: atlases.map(view => ({ id: view.id, frames: view.frames, atlasBytes: view.data.length })),
    sceneTime: 7, compensationPixels: config.compensationPixels,
  };
  await writeFile(resolve(directory, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  return manifest;
}

const mime = { ".html": "text/html", ".js": "text/javascript", ".mjs": "text/javascript", ".svg": "image/svg+xml", ".webp": "image/webp", ".css": "text/css", ".json": "application/json", ".md": "text/plain" };
const server = createServer(async (request, response) => {
  try {
    const url = new URL(request.url, `http://127.0.0.1:${port}`);
    if (request.method === "POST") {
      if (request.headers.origin !== `http://127.0.0.1:${port}`) { response.writeHead(403).end("Local capture page only"); return; }
      if (url.pathname === "/capture/build") {
        response.setHeader("Content-Type", "application/json");
        response.end(JSON.stringify(await build())); return;
      }
      const match = /^\/capture\/atlas\/(overview|library)$/.exec(url.pathname);
      if (!match) { response.writeHead(404).end(); return; }
      const chunks = []; let size = 0;
      for await (const chunk of request) {
        size += chunk.length;
        if (size > 16 * 1048576) { response.writeHead(413).end("Atlas too large"); return; }
        chunks.push(chunk);
      }
      const data = Buffer.concat(chunks);
      if (data.toString("ascii", 0, 4) !== "RIFF" || data.toString("ascii", 8, 12) !== "WEBP") throw new Error("Expected WebP atlas");
      await writeFile(resolve(cache, `${match[1]}.webp`), data);
      response.end("Saved"); return;
    }
    response.setHeader("Cache-Control", "no-store");
    if (url.pathname === "/capture/config") { response.setHeader("Content-Type", "application/json"); response.end(JSON.stringify(config)); return; }
    const path = resolve(root, "." + decodeURIComponent(url.pathname === "/" ? "/examples/island-profile-spike/capture.html" : url.pathname));
    if (!path.startsWith(root + sep) || path.includes(sep + ".git" + sep)) { response.writeHead(403).end(); return; }
    const content = await readFile(path);
    response.setHeader("Content-Type", mime[extname(path)] || "application/octet-stream");
    response.end(content);
  } catch (error) { response.writeHead(error.code === "ENOENT" ? 404 : 500).end(error.message); }
});
if (process.argv.includes("--build")) {
  console.log(JSON.stringify(await build(), null, 2));
} else {
  server.listen(port, "127.0.0.1", () => console.log(`Capture: http://127.0.0.1:${port}/`));
}
