import { assetName, escapeHtml, previewFor } from "./output.mjs";

export function profileReadme(config, content) {
  const { views } = content;
  return `<!-- Generated by jasvir/jasvir.github.io. Edit dist/content.js and profile/config.js, then rebuild. -->
${views.map((view, index) => `<details name="island-profile-view"${index === 0 ? " open" : ""}>
<summary>${escapeHtml(view.title)}</summary>
<p align="left"><img src="./${assetName(view)}" width="100%" alt="${escapeHtml(view.title)} — animated island view"></p>
<p><a href="${escapeHtml(view.href)}">Expand...</a></p>
</details>`).join("\n\n")}
`;
}

export function profilePreview(config, content) {
  return previewFor({ ...config, views: content.views, expandOnly: true });
}

export function validateSvg(svg) {
  if (/<script\b|<foreignObject\b|\bon\w+=/i.test(svg)) throw new Error("Export contains interactive markup");
  const refs = [...svg.matchAll(/\bhref="([^"]+)"/g)];
  if (refs.length !== 1 || !refs[0][1].startsWith("data:image/webp;base64,")) throw new Error("Export must contain one self-contained WebP atlas");
  if (!svg.includes("prefers-reduced-motion")) throw new Error("Reduced motion is missing");
}

export function validateConfig(config) {
  for (const key of ["width", "height", "columns", "overviewFrames", "highlightFrames"]) {
    if (!Number.isInteger(config[key]) || config[key] <= 0) throw new Error(`Invalid export ${key}`);
  }
  if (config.width !== 600 || config.height !== 360) throw new Error("Current card layout requires a 600 × 360 export");
  if (config.overviewFrames < 2 || config.highlightFrames < 2) throw new Error("At least two frames are required");
  if (config.columns * config.width > 16383 || Math.ceil(Math.max(config.overviewFrames, config.highlightFrames) / config.columns) * config.height > 16383) throw new Error("Atlas exceeds WebP dimensions");
  if (!(config.quality > 0 && config.quality <= 1) || !Number.isFinite(config.sceneTime) || config.sceneTime < 0) throw new Error("Invalid render quality or scene time");
  if (!Number.isFinite(config.compensationPixels) || config.compensationPixels < 0) throw new Error("Invalid alignment compensation");
  for (const key of ["maxAssetBytes", "maxTotalBytes"]) if (!Number.isSafeInteger(config[key]) || config[key] <= 0) throw new Error(`Invalid ${key}`);
  if (!/^https?:\/\//i.test(config.siteUrl)) throw new Error("Invalid full-site URL");
}
